-- ==============================================================================
-- SCRIPT SETUP DATABASE SUPABASE: MODUL SURAT TUGAS & PERJALANAN DINAS (APA)
-- BPS KABUPATEN RAJA AMPAT
-- ==============================================================================

-- 1. TABEL KAMUS_POK (Mata Anggaran Kegiatan / POK)
CREATE TABLE IF NOT EXISTS public.kamus_pok (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_mak TEXT,
    deskripsi TEXT,
    tahun INT DEFAULT 2026,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.kamus_pok ADD COLUMN IF NOT EXISTS kode_mak TEXT;
ALTER TABLE public.kamus_pok ADD COLUMN IF NOT EXISTS deskripsi TEXT;
ALTER TABLE public.kamus_pok ADD COLUMN IF NOT EXISTS tahun INT DEFAULT 2026;
CREATE INDEX IF NOT EXISTS idx_kamus_pok_kode ON public.kamus_pok(kode_mak);

-- 2. TABEL MITRA (Mitra Statistik dengan NIP placeholder MITRA-{tahun}-{id 3 digit})
CREATE TABLE IF NOT EXISTS public.mitra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mitra_nip TEXT,
    nama TEXT,
    jk TEXT DEFAULT 'Laki-laki',
    alamat TEXT,
    jabatan TEXT DEFAULT 'Mitra Statistik',
    posisi TEXT DEFAULT 'Petugas Pendataan Lapangan',
    tahun INT DEFAULT 2026,
    no_hp TEXT,
    instansi TEXT DEFAULT 'BPS Kabupaten Raja Ampat',
    created_at TIMESTAMPTZ DEFAULT now()
);
-- Pastikan kolom yang mungkin belum ada di tabel mitra lama langsung ditambahkan:
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS tahun INT DEFAULT 2026;
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS no_hp TEXT;
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS instansi TEXT DEFAULT 'BPS Kabupaten Raja Ampat';
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS mitra_nip TEXT;
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS nama TEXT;
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS jk TEXT DEFAULT 'Laki-laki';
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS alamat TEXT;
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS jabatan TEXT DEFAULT 'Mitra Statistik';
ALTER TABLE public.mitra ADD COLUMN IF NOT EXISTS posisi TEXT DEFAULT 'Petugas Pendataan Lapangan';
CREATE INDEX IF NOT EXISTS idx_mitra_nip ON public.mitra(mitra_nip);

-- 3. TABEL SURAT_TUGAS (Mendukung skema lengkap Sistem Automasi Pekerjaan Administrasi (APA))
CREATE TABLE IF NOT EXISTS public.surat_tugas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    nomor_surat TEXT,
    nomor_urut INT,
    tanggal_surat TEXT,
    tgl_surat TEXT,
    tanggal_berangkat TEXT,
    tanggal_kembali TEXT,
    waktu_pelaksanaan_text TEXT,
    waktu_pelaksanaan TEXT,
    tgl_mulai TEXT,
    tgl_selesai TEXT,
    perihal TEXT,
    tujuan TEXT,
    tempat_tujuan TEXT,
    pegawai_nip JSONB DEFAULT '[]'::jsonb,
    pegawai_list JSONB DEFAULT '[]'::jsonb,
    pegawai_nip_list JSONB DEFAULT '[]'::jsonb,
    bertugas_sebagai JSONB DEFAULT '[]'::jsonb,
    menimbang_custom TEXT,
    menimbang TEXT,
    alat_angkutan TEXT DEFAULT 'Kendaraan Dinas / Sewa',
    pembebanan TEXT,
    pok_id TEXT,
    penandatangan_nip TEXT,
    penandatangan_nama TEXT,
    tipe TEXT DEFAULT 'surat_tugas',
    tipe_surat TEXT DEFAULT 'surat_tugas',
    jumlah_responden INT DEFAULT 1,
    tempat_terbit TEXT DEFAULT 'Waisai',
    status TEXT DEFAULT 'menunggu', -- 'menunggu' | 'selesai'
    nomor_spd TEXT,
    nomor_spd_urut INT,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Pastikan semua kolom pendukung ada jika tabel surat_tugas sudah dibuat sebelumnya:
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS nomor_surat TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS nomor_urut INT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tanggal_surat TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tgl_surat TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tanggal_berangkat TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tanggal_kembali TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS waktu_pelaksanaan_text TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS waktu_pelaksanaan TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tgl_mulai TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tgl_selesai TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS perihal TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tujuan TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tempat_tujuan TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS pegawai_nip JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS pegawai_list JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS pegawai_nip_list JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS bertugas_sebagai JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS menimbang_custom TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS menimbang TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS alat_angkutan TEXT DEFAULT 'Kendaraan Dinas / Sewa';
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS pembebanan TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS pok_id TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS penandatangan_nip TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS penandatangan_nama TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tipe TEXT DEFAULT 'surat_tugas';
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tipe_surat TEXT DEFAULT 'surat_tugas';
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS jumlah_responden INT DEFAULT 1;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS tempat_terbit TEXT DEFAULT 'Waisai';
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'menunggu';
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS nomor_spd TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS nomor_spd_urut INT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.surat_tugas ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_surat_tugas_status ON public.surat_tugas(status);
CREATE INDEX IF NOT EXISTS idx_surat_tugas_user_id ON public.surat_tugas(user_id);
CREATE INDEX IF NOT EXISTS idx_surat_tugas_created_at ON public.surat_tugas(created_at);

-- 4. PENGATURAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.kamus_pok ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mitra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.surat_tugas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access kamus_pok" ON public.kamus_pok;
CREATE POLICY "Public access kamus_pok" ON public.kamus_pok FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access mitra" ON public.mitra;
CREATE POLICY "Public access mitra" ON public.mitra FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access surat_tugas" ON public.surat_tugas;
CREATE POLICY "Public access surat_tugas" ON public.surat_tugas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 5. BUCKET STORAGE UNTUK TEMPLATE & PREVIEW DOKUMEN WORD
INSERT INTO storage.buckets (id, name, public)
VALUES 
    ('template', 'template', true),
    ('surat-tugas-preview', 'surat-tugas-preview', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

DROP POLICY IF EXISTS "Storage access template" ON storage.objects;
CREATE POLICY "Storage access template" ON storage.objects FOR ALL TO anon, authenticated USING (bucket_id = 'template') WITH CHECK (bucket_id = 'template');

DROP POLICY IF EXISTS "Storage access surat-tugas-preview" ON storage.objects;
CREATE POLICY "Storage access surat-tugas-preview" ON storage.objects FOR ALL TO anon, authenticated USING (bucket_id = 'surat-tugas-preview') WITH CHECK (bucket_id = 'surat-tugas-preview');

-- 6. SEED DATA KAMUS_POK (Daftar MAK Kegiatan BPS Kabupaten Raja Ampat)
-- Menggunakan NOT EXISTS agar aman tanpa ketergantungan pada constraint unik
INSERT INTO public.kamus_pok (kode_mak, deskripsi, tahun)
SELECT p.kode_mak, p.deskripsi, p.tahun
FROM (
    VALUES
    ('2901.BMA.006.051.A.524111', 'Belanja Perjalanan Dinas Biasa Subbagian Umum BPS Kabupaten Raja Ampat', 2026),
    ('2901.EBA.994.051.A.524111', 'Perjalanan Dinas Survei Angkatan Kerja Nasional (SAKERNAS) Semesteran', 2026),
    ('2901.EBA.994.051.B.524113', 'Perjalanan Dinas Survei Sosial Ekonomi Nasional (SUSENAS) Kor dan Konsumsi', 2026),
    ('2901.QDB.001.051.A.524111', 'Perjalanan Dinas Statistik Pertanian, Tanaman Pangan, Hortikultura, dan Perkebunan', 2026),
    ('2901.QDB.002.051.A.524111', 'Perjalanan Dinas Survei Perikanan dan Kelautan Wilayah Kepulauan Raja Ampat', 2026),
    ('2901.QDC.001.051.A.524111', 'Perjalanan Dinas Statistik Distribusi, Hotel, Restoran, dan Wisata Bahari', 2026),
    ('2901.QDC.002.051.A.524111', 'Perjalanan Dinas Survei Harga Produsen dan Konsumen Pedesaan', 2026),
    ('2901.QDD.003.051.A.524111', 'Perjalanan Dinas Neraca Wilayah, PDRB, dan Analisis Statistik Lintas Sektor', 2026),
    ('2901.QDE.004.051.A.524111', 'Perjalanan Dinas Integrasi Pengolahan, Diseminasi, dan Rekomendasi Statistik', 2026),
    ('2901.WA.001.051.A.524111', 'Perjalanan Dinas Pembinaan Desa Cinta Statistik (Desa Cantik) Raja Ampat', 2026)
) AS p(kode_mak, deskripsi, tahun)
WHERE NOT EXISTS (
    SELECT 1 FROM public.kamus_pok existing WHERE existing.kode_mak = p.kode_mak
);

-- 7. SEED DATA MITRA (Daftar Mitra Statistik BPS Raja Ampat)
-- Menggunakan NOT EXISTS agar aman tanpa ketergantungan pada constraint unik
INSERT INTO public.mitra (mitra_nip, nama, jk, alamat, jabatan, posisi, tahun, instansi)
SELECT m.mitra_nip, m.nama, m.jk, m.alamat, m.jabatan, m.posisi, m.tahun, m.instansi
FROM (
    VALUES
    ('MITRA-2026-001', 'Yohanes Mambrasar', 'Laki-laki', 'Waisai Kota, Distrik Kota Waisai', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-002', 'Maria Dimara', 'Perempuan', 'Kelurahan Sapordanko, Distrik Kota Waisai', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-003', 'Simon Mayor', 'Laki-laki', 'Kampung Saonek, Distrik Waigeo Selatan', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-004', 'Naomi Fakdawer', 'Perempuan', 'Kampung Warsambin, Distrik Teluk Mayalibit', 'Mitra Statistik', 'Pemeriksa Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-005', 'Paulus Gaman', 'Laki-laki', 'Kampung Yenbeser, Distrik Waigeo Selatan', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-006', 'Beatrix Burdam', 'Perempuan', 'Waisai Kota, Distrik Kota Waisai', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-007', 'Markus Sauyai', 'Laki-laki', 'Kampung Friwen, Distrik Waigeo Selatan', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-008', 'Sarah Arfan', 'Perempuan', 'Kampung Lopintol, Distrik Teluk Mayalibit', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-009', 'Dominggus Rumbewas', 'Laki-laki', 'Kampung Yembekaki, Distrik Waigeo Timur', 'Mitra Statistik', 'Pencacah Lapangan', 2026, 'BPS Kabupaten Raja Ampat'),
    ('MITRA-2026-010', 'Fransina Wader', 'Perempuan', 'Waisai Kota, Distrik Kota Waisai', 'Mitra Statistik', 'Pemeriksa Lapangan', 2026, 'BPS Kabupaten Raja Ampat')
) AS m(mitra_nip, nama, jk, alamat, jabatan, posisi, tahun, instansi)
WHERE NOT EXISTS (
    SELECT 1 FROM public.mitra existing WHERE existing.mitra_nip = m.mitra_nip OR existing.nama = m.nama
);

-- 8. FUNGSI RPC: AMBIL NOMOR URUT BERIKUTNYA UNTUK SURAT TUGAS & SPD
CREATE OR REPLACE FUNCTION public.get_next_nomor_surat_tugas(p_tahun INT)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_max INT;
BEGIN
    SELECT COALESCE(MAX(nomor_urut), 0) INTO v_max
    FROM public.surat_tugas
    WHERE (EXTRACT(YEAR FROM created_at) = p_tahun OR tgl_surat LIKE '%' || p_tahun::text || '%' OR tanggal_surat LIKE '%' || p_tahun::text || '%');

    RETURN v_max + 1;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_next_nomor_surat_tugas(INT) TO anon, authenticated;
