-- ==============================================================================
-- SCRIPT SETUP DATABASE SUPABASE LENGKAP: SISTEM AUTOMASI PEKERJAAN ADMINISTRASI (APA)
-- BPS KABUPATEN RAJA AMPAT
-- Jalankan seluruh script ini di menu "SQL Editor" pada dashboard Supabase Anda.
-- ==============================================================================

-- 1. AKTIFKAN EKSTENSI KRIPTOGRAFI (PGCRYPTO)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. TABEL 1: USERS
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    must_change_password BOOLEAN DEFAULT TRUE NOT NULL,
    full_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    last_login TIMESTAMPTZ,
    role TEXT DEFAULT 'user' NOT NULL,
    roles JSONB DEFAULT '["user"]'::jsonb NOT NULL,
    notifikasi_last_read_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);

-- 3. TABEL 2: DATA_PEGAWAI
-- Menggunakan kolom username untuk relasi ke tabel users, dan pegawai_nip sebagai kolom referensi utama ke tabel-tabel riwayat
CREATE TABLE IF NOT EXISTS public.data_pegawai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE REFERENCES public.users(username) ON UPDATE CASCADE ON DELETE SET NULL,
    pegawai_nip TEXT UNIQUE NOT NULL,
    karpeg TEXT,
    ttl TEXT,
    jk TEXT,
    unit_kerja TEXT DEFAULT 'BPS Kabupaten Raja Ampat',
    pendidikan_terakhir TEXT,
    foto_url TEXT,
    status_kepegawaian TEXT DEFAULT 'aktif',
    tanggal_pensiun TEXT,
    keterangan_status TEXT,
    nip_lama TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_data_pegawai_nip ON public.data_pegawai(pegawai_nip);
CREATE INDEX IF NOT EXISTS idx_data_pegawai_username ON public.data_pegawai(username);

-- 4. TABEL 3: RIWAYAT_JABATAN
-- NIP menjadi kolom referensi ke data_pegawai(pegawai_nip)
CREATE TABLE IF NOT EXISTS public.riwayat_jabatan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_nip TEXT NOT NULL REFERENCES public.data_pegawai(pegawai_nip) ON UPDATE CASCADE ON DELETE CASCADE,
    jabatan TEXT NOT NULL,
    tmt TEXT,
    tmt_ikut_pak TEXT,
    jenis TEXT DEFAULT 'utama',
    tmt_selesai TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_riwayat_jabatan_nip ON public.riwayat_jabatan(pegawai_nip);

-- 5. TABEL 4: RIWAYAT_PANGKAT_GOLONGAN
-- NIP menjadi kolom referensi ke data_pegawai(pegawai_nip)
CREATE TABLE IF NOT EXISTS public.riwayat_pangkat_golongan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_nip TEXT NOT NULL REFERENCES public.data_pegawai(pegawai_nip) ON UPDATE CASCADE ON DELETE CASCADE,
    pangkat TEXT NOT NULL,
    golongan TEXT NOT NULL,
    tmt TEXT,
    tmt_ikut_pak TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_riwayat_pangkat_nip ON public.riwayat_pangkat_golongan(pegawai_nip);

-- 6. TABEL 5: RIWAYAT_ANGKA_KREDIT
-- NIP menjadi kolom referensi ke data_pegawai(pegawai_nip)
CREATE TABLE IF NOT EXISTS public.riwayat_angka_kredit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_nip TEXT NOT NULL REFERENCES public.data_pegawai(pegawai_nip) ON UPDATE CASCADE ON DELETE CASCADE,
    angka_kredit NUMERIC(10, 3) NOT NULL DEFAULT 0,
    tmt TEXT,
    periode_tahun INT,
    periode_bulan_awal INT,
    periode_bulan_akhir INT,
    periode_label TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_riwayat_ak_nip ON public.riwayat_angka_kredit(pegawai_nip);

-- 7. TABEL 6: RIWAYAT_GELAR
-- NIP menjadi kolom referensi ke data_pegawai(pegawai_nip)
CREATE TABLE IF NOT EXISTS public.riwayat_gelar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_nip TEXT NOT NULL REFERENCES public.data_pegawai(pegawai_nip) ON UPDATE CASCADE ON DELETE CASCADE,
    gelar_depan TEXT,
    gelar_belakang TEXT,
    tmt TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_riwayat_gelar_nip ON public.riwayat_gelar(pegawai_nip);

-- ==============================================================================
-- 8. PENGATURAN HAK AKSES & ROW LEVEL SECURITY (RLS)
-- Role Admin: dapat menambah, mengedit, dan menghapus seluruh tabel
-- Role User: dapat membaca semua tabel, serta menambah/mengupdate data_pegawai dan riwayat
-- ==============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_pegawai ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.riwayat_jabatan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.riwayat_pangkat_golongan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.riwayat_angka_kredit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.riwayat_gelar ENABLE ROW LEVEL SECURITY;

-- Kebijakan RLS Terbuka untuk Operasi Web (Aman karena password_hash tidak diekspos langsung)
DROP POLICY IF EXISTS "Public select users" ON public.users;
CREATE POLICY "Public select users" ON public.users FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "All select data_pegawai" ON public.data_pegawai;
CREATE POLICY "All select data_pegawai" ON public.data_pegawai FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "All select riwayat_jabatan" ON public.riwayat_jabatan;
CREATE POLICY "All select riwayat_jabatan" ON public.riwayat_jabatan FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "All select riwayat_pangkat" ON public.riwayat_pangkat_golongan;
CREATE POLICY "All select riwayat_pangkat" ON public.riwayat_pangkat_golongan FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "All select riwayat_ak" ON public.riwayat_angka_kredit;
CREATE POLICY "All select riwayat_ak" ON public.riwayat_angka_kredit FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "All select riwayat_gelar" ON public.riwayat_gelar;
CREATE POLICY "All select riwayat_gelar" ON public.riwayat_gelar FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ==============================================================================
-- 9. FUNGSI RPC: AUTENTIKASI LOGIN & GANTI PASSWORD
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.login_user(
    p_username TEXT,
    p_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_user RECORD;
    v_pegawai RECORD;
BEGIN
    p_username := trim(p_username);

    SELECT id, username, password_hash, must_change_password, full_name, role, roles
    INTO v_user
    FROM public.users
    WHERE lower(username) = lower(p_username);

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'Username atau password salah');
    END IF;

    IF v_user.password_hash = extensions.crypt(p_password, v_user.password_hash) THEN
        UPDATE public.users SET last_login = now() WHERE id = v_user.id;

        -- Ambil NIP yang bersesuaian di data_pegawai
        SELECT pegawai_nip INTO v_pegawai FROM public.data_pegawai WHERE lower(username) = lower(v_user.username);

        RETURN jsonb_build_object(
            'success', true,
            'user', jsonb_build_object(
                'id', v_user.id,
                'username', v_user.username,
                'full_name', v_user.full_name,
                'role', v_user.role,
                'roles', v_user.roles,
                'must_change_password', v_user.must_change_password,
                'pegawai_nip', v_pegawai.pegawai_nip
            )
        );
    ELSE
        RETURN jsonb_build_object('success', false, 'message', 'Username atau password salah');
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.change_user_password(
    p_username TEXT,
    p_old_password TEXT,
    p_new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_user RECORD;
BEGIN
    p_username := trim(p_username);

    IF length(p_new_password) < 6 OR p_new_password !~ '[A-Za-z]' OR p_new_password !~ '[0-9]' THEN
        RETURN jsonb_build_object('success', false, 'message', 'Password minimal 6 karakter dan harus kombinasi huruf serta angka');
    END IF;

    SELECT id, password_hash INTO v_user FROM public.users WHERE lower(username) = lower(p_username);

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'Pengguna tidak ditemukan');
    END IF;

    IF v_user.password_hash != extensions.crypt(p_old_password, v_user.password_hash) THEN
        RETURN jsonb_build_object('success', false, 'message', 'Password lama tidak sesuai');
    END IF;

    UPDATE public.users
    SET password_hash = extensions.crypt(p_new_password, extensions.gen_salt('bf', 10)),
        must_change_password = FALSE,
        last_login = now()
    WHERE id = v_user.id;

    RETURN jsonb_build_object('success', true, 'message', 'Password berhasil diperbarui');
END;
$$;

-- 10. FUNGSI RPC: AMBIL SELURUH DATA PROFIL PEGAWAI BERDASARKAN USERNAME
CREATE OR REPLACE FUNCTION public.get_pegawai_profile(p_username TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user RECORD;
    v_pegawai RECORD;
    v_nip TEXT;
    v_jabatan JSONB;
    v_pangkat JSONB;
    v_angka_kredit JSONB;
    v_gelar JSONB;
BEGIN
    -- 1. Ambil data user
    SELECT id, username, full_name, role, roles, must_change_password
    INTO v_user
    FROM public.users
    WHERE lower(username) = lower(trim(p_username));

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'User tidak ditemukan');
    END IF;

    -- 2. Ambil data_pegawai berdasarkan username
    SELECT * INTO v_pegawai
    FROM public.data_pegawai
    WHERE lower(username) = lower(v_user.username);

    v_nip := v_pegawai.pegawai_nip;

    -- 3. Ambil riwayat berdasarkan pegawai_nip
    SELECT COALESCE(jsonb_agg(to_jsonb(j) ORDER BY j.id DESC), '[]'::jsonb)
    INTO v_jabatan
    FROM public.riwayat_jabatan j
    WHERE j.pegawai_nip = v_nip;

    SELECT COALESCE(jsonb_agg(to_jsonb(p) ORDER BY p.id DESC), '[]'::jsonb)
    INTO v_pangkat
    FROM public.riwayat_pangkat_golongan p
    WHERE p.pegawai_nip = v_nip;

    SELECT COALESCE(jsonb_agg(to_jsonb(a) ORDER BY a.periode_tahun DESC, a.periode_bulan_akhir DESC, a.id DESC), '[]'::jsonb)
    INTO v_angka_kredit
    FROM public.riwayat_angka_kredit a
    WHERE a.pegawai_nip = v_nip;

    SELECT COALESCE(jsonb_agg(to_jsonb(g) ORDER BY g.id DESC), '[]'::jsonb)
    INTO v_gelar
    FROM public.riwayat_gelar g
    WHERE g.pegawai_nip = v_nip;

    RETURN jsonb_build_object(
        'success', true,
        'user', to_jsonb(v_user),
        'data_pegawai', to_jsonb(v_pegawai),
        'riwayat_jabatan', v_jabatan,
        'riwayat_pangkat_golongan', v_pangkat,
        'riwayat_angka_kredit', v_angka_kredit,
        'riwayat_gelar', v_gelar
    );
END;
$$;

-- Berikan izin akses RPC
GRANT EXECUTE ON FUNCTION public.login_user(TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.change_user_password(TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_pegawai_profile(TEXT) TO anon, authenticated;

-- ==============================================================================
-- 11. SEED DATA AWAL DARI FILE-FILE CSV
-- ==============================================================================

-- A. INSERT USERS (25 Pengguna)
INSERT INTO public.users (id, username, password_hash, must_change_password, full_name, role, roles)
VALUES
(1, 'frida', crypt('123456', gen_salt('bf', 10)), TRUE, 'Frida Irian S. Ompusunggu', 'user', '["user"]'::jsonb),
(2, 'andriew', crypt('123456', gen_salt('bf', 10)), TRUE, 'Andrie Wardani', 'user', '["user"]'::jsonb),
(3, 'derek', crypt('123456', gen_salt('bf', 10)), TRUE, 'Derek Mandowen', 'user', '["user"]'::jsonb),
(4, 'frida.buratehi', crypt('123456', gen_salt('bf', 10)), TRUE, 'Frida Buratehi', 'user', '["user"]'::jsonb),
(5, 'maulana.tahir', crypt('123456', gen_salt('bf', 10)), TRUE, 'Maulana Tahir', 'user', '["user"]'::jsonb),
(6, 'abdillah.humam', crypt('123456', gen_salt('bf', 10)), TRUE, 'Abdillah Humam', 'user', '["user"]'::jsonb),
(7, 'ikbal.ism', crypt('123456', gen_salt('bf', 10)), TRUE, 'Ikbal Ismail', 'user', '["user"]'::jsonb),
(8, 'lestari.amir', crypt('123456', gen_salt('bf', 10)), TRUE, 'Lestari Irfandi Amir', 'user', '["user"]'::jsonb),
(9, 'bagas.sakti', crypt('123456', gen_salt('bf', 10)), TRUE, 'Bagas Indra Sakti', 'user', '["user"]'::jsonb),
(10, 'sausan.zulfa', crypt('123456', gen_salt('bf', 10)), TRUE, 'Sausan Zulfa Faizah', 'user', '["user"]'::jsonb),
(11, 'alijumati', crypt('123456', gen_salt('bf', 10)), TRUE, 'Muchammad Ali Jumati', 'user', '["user"]'::jsonb),
(12, 'novalin', crypt('123456', gen_salt('bf', 10)), TRUE, 'Novalin P. Wapai', 'user', '["user"]'::jsonb),
(13, 'gerda', crypt('123456', gen_salt('bf', 10)), TRUE, 'Gerda Y. Kalasuat', 'user', '["user"]'::jsonb),
(14, 'rizal.akbar', crypt('123456', gen_salt('bf', 10)), TRUE, 'Rizal Akbar Komarudin', 'admin', '["admin", "user"]'::jsonb),
(15, 'jandriana.ramandei', crypt('123456', gen_salt('bf', 10)), TRUE, 'Jandriana Ramandei', 'user', '["user"]'::jsonb),
(16, 'elok', crypt('123456', gen_salt('bf', 10)), TRUE, 'Elok Agustina', 'user', '["user"]'::jsonb),
(17, 'zidna.inayatika', crypt('123456', gen_salt('bf', 10)), TRUE, 'Zidna Inayatika', 'user', '["user"]'::jsonb),
(18, 'haidar.nabil', crypt('123456', gen_salt('bf', 10)), TRUE, 'Haidar Nabil', 'user', '["user"]'::jsonb),
(19, 'syayu.hanana', crypt('123456', gen_salt('bf', 10)), TRUE, 'Syayu Hanana Yohana Stefani', 'user', '["user"]'::jsonb),
(20, 'aris.munandar', crypt('123456', gen_salt('bf', 10)), TRUE, 'M. Aris Munandar', 'user', '["user"]'::jsonb),
(21, 'dwiayua', crypt('123456', gen_salt('bf', 10)), TRUE, 'Dwi Ayu Andriani', 'user', '["user"]'::jsonb),
(22, 'figri.alrasjid', crypt('123456', gen_salt('bf', 10)), TRUE, 'Figri Al - Rasjid Abdullah', 'user', '["user"]'::jsonb),
(23, 'khusenali', crypt('123456', gen_salt('bf', 10)), TRUE, 'M. Khusen Ali Al Anjabi', 'user', '["user"]'::jsonb),
(24, 'arikhzasaputri', crypt('123456', gen_salt('bf', 10)), TRUE, 'Arikhza Saputri', 'user', '["user"]'::jsonb),
(25, 'nurhaidas', crypt('123456', gen_salt('bf', 10)), TRUE, 'Nurhaida Sirun', 'user', '["user"]'::jsonb)
ON CONFLICT (username) DO UPDATE 
SET password_hash = EXCLUDED.password_hash,
    must_change_password = EXCLUDED.must_change_password,
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    roles = EXCLUDED.roles;

-- B. INSERT DATA_PEGAWAI (25 Pegawai)
INSERT INTO public.data_pegawai (id, username, pegawai_nip, karpeg, ttl, jk, unit_kerja, pendidikan_terakhir, foto_url, status_kepegawaian, tanggal_pensiun, keterangan_status, nip_lama)
VALUES
(1, 'andriew', '198904192012111001', 'A 14002573', 'Sorong, 19 April 1989', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340055728'),
(2, 'derek', '198303182011011007', 'A 00001557', 'Biak Numfor, 18 Maret 1983', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, NULL),
(3, 'frida.buratehi', '197912122010032002', 'Q 068614', 'Sorong, 12 Desember 1979', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340054043'),
(4, 'maulana.tahir', '199209162014121001', 'A 14003354', 'Sorong, 16 September 1992', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S2', NULL, 'aktif', NULL, NULL, '340057127'),
(5, 'abdillah.humam', '199510152018021001', 'A 14005529', 'Pekalongan, 15 Oktober 1995', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340058100'),
(6, 'ikbal.ism', '198804022011011007', 'Q 068626', 'Manokwari, 02 April 1988', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340055686'),
(7, 'lestari.amir', '199207162019031001', 'A 14009964', 'Ujung Pandang, 16 Juli 1992', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340059346'),
(8, 'bagas.sakti', '199610012019011003', 'A 14009961', 'Nganjuk, 01 Oktober 1996', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340058640'),
(9, 'sausan.zulfa', '199504162018022001', 'A 14007420', 'Magelang, 16 April 1995', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340058486'),
(10, 'alijumati', '197809102007011002', NULL, 'Saonek, 10 September 1978', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'SMA', NULL, 'aktif', NULL, NULL, NULL),
(11, 'novalin', '198211202011012011', 'A 00001561', 'Sorong, 20 November 1982', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340055691'),
(12, 'gerda', '198801242011012016', 'Q 068625', 'Sorong, 24 Januari 1988', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340055684'),
(13, 'rizal.akbar', '199903302019121001', 'A 14009963', 'Kaimana, 30 Maret 1999', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'DIII', NULL, 'aktif', NULL, NULL, '340059896'),
(14, 'jandriana.ramandei', '199801062019122001', 'A 14009962', 'Sorong, 06 Januari 1998', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340059577'),
(15, 'elok', '198908262012112001', 'A 00000496', 'Pekalongan, 26 Agustus 1989', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S2', NULL, 'aktif', NULL, NULL, '340055775'),
(16, 'zidna.inayatika', '199902212021042001', NULL, 'Sleman, 21 Februari 1999', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340060365'),
(17, 'haidar.nabil', '199903302022011001', 'A202300146918', 'Kediri, 30 Maret 1999', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340060668'),
(18, 'syayu.hanana', '199803012022032017', 'A202300146885', 'Ujung Pandang, 01 Maret 1998', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'DIII', NULL, 'aktif', NULL, NULL, '340061556'),
(19, 'aris.munandar', '200003232023021002', NULL, 'Medan, 23 Maret 2000', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340061875'),
(20, 'dwiayua', '200103272023102002', 'A202400023433', 'Grobogan, 27 Maret 2001', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340062413'),
(21, 'figri.alrasjid', '200107052024121001', 'A202500034730', 'Surabaya, 05 Juli 2001', 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340063171'),
(22, 'nurhaidas', '196803201994012001', 'G 052556', 'Jayapura, 20 Maret 1968', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'pensiun', '3/31/2026', NULL, '340014127'),
(23, 'khusenali', '200204152026031001', NULL, NULL, 'Laki-laki', 'BPS Kabupaten Raja Ampat', 'S1/DIV', NULL, 'aktif', NULL, NULL, '340066333'),
(24, 'arikhzasaputri', '200404122026032001', NULL, NULL, 'Perempuan', 'BPS Kabupaten Raja Ampat', 'DIII', NULL, 'aktif', NULL, NULL, '340066132'),
(25, 'frida', '198604072009022004', 'P129652', 'Jayapura, 07 April 1986', 'Perempuan', 'BPS Kabupaten Raja Ampat', 'S2', NULL, 'aktif', NULL, NULL, '340050100')
ON CONFLICT (pegawai_nip) DO UPDATE 
SET username = EXCLUDED.username,
    karpeg = EXCLUDED.karpeg,
    ttl = EXCLUDED.ttl,
    jk = EXCLUDED.jk,
    unit_kerja = EXCLUDED.unit_kerja,
    pendidikan_terakhir = EXCLUDED.pendidikan_terakhir,
    status_kepegawaian = EXCLUDED.status_kepegawaian,
    tanggal_pensiun = EXCLUDED.tanggal_pensiun,
    nip_lama = EXCLUDED.nip_lama;

-- C. INSERT RIWAYAT_JABATAN
INSERT INTO public.riwayat_jabatan (id, pegawai_nip, jabatan, tmt, tmt_ikut_pak, jenis, tmt_selesai)
VALUES
(1, '196803201994012001', 'Kepala BPS Kabupaten Raja Ampat', '6/29/2020', '6/29/2020', 'utama', '3/31/2026'),
(2, '198904192012111001', 'Kepala Subbagian Umum', '12/22/2020', '12/22/2020', 'utama', NULL),
(3, '198303182011011007', 'Pelaksana', '1/1/2015', '1/1/2015', 'utama', NULL),
(4, '197912122010032002', 'Statistisi Ahli Muda', '12/22/2020', '12/22/2020', 'utama', NULL),
(5, '199209162014121001', 'Statistisi Ahli Muda', '1/9/2024', '1/9/2024', 'utama', NULL),
(6, '199510152018021001', 'Statistisi Ahli Muda', '6/1/2024', '1/31/2024', 'utama', NULL),
(7, '198804022011011007', 'Statistisi Ahli Pertama', '6/26/2023', '12/31/2022', 'utama', NULL),
(8, '199207162019031001', 'Statistisi Ahli Pertama', '7/9/2021', '7/9/2021', 'utama', NULL),
(9, '199610012019011003', 'Statistisi Ahli Pertama', '7/9/2021', '7/9/2021', 'utama', NULL),
(10, '199504162018022001', 'Statistisi Ahli Pertama', '10/31/2024', '10/31/2024', 'utama', NULL),
(11, '197809102007011002', 'Pelaksana', '1/1/2015', '1/1/2015', 'utama', NULL),
(12, '198211202011012011', 'Statistisi Ahli Muda', '6/26/2023', '12/31/2022', 'utama', NULL),
(13, '198801242011012016', 'Statistisi Ahli Muda', '6/26/2023', '12/31/2022', 'utama', NULL),
(14, '199903302019121001', 'Statistisi Pelaksana', '6/2/2021', '6/2/2021', 'utama', NULL),
(15, '199801062019122001', 'Statistisi Ahli Pertama', '5/31/2022', '5/31/2022', 'utama', NULL),
(16, '198908262012112001', 'Statistisi Ahli Muda', '6/8/2023', '12/31/2022', 'utama', NULL),
(17, '199902212021042001', 'Statistisi Ahli Pertama', '3/7/2023', '12/31/2022', 'utama', NULL),
(18, '199903302022011001', 'Statistisi Ahli Pertama', '1/31/2023', '12/31/2022', 'utama', NULL),
(19, '199803012022032017', 'Statistisi Pelaksana', '3/8/2023', '12/31/2022', 'utama', NULL),
(20, '200003232023021002', 'Pranata Komputer Ahli Pertama', '3/1/2024', '2/28/2023', 'utama', NULL),
(21, '200103272023102002', 'Statistisi Ahli Pertama', '10/3/2024', '10/31/2023', 'utama', NULL),
(22, '200107052024121001', 'Pelaksana', '12/1/2024', '12/1/2024', 'utama', NULL),
(23, '200107052024121001', 'Pranata Komputer Ahli Pertama', '12/11/2025', '12/1/2024', 'utama', NULL),
(24, '198904192012111001', 'Plt. Kepala Badan Pusat Statistik', '4/1/2026', NULL, 'lainnya', '7/1/2026'),
(25, '199510152018021001', 'Pejabat Pembuat Komitmen', '1/1/2021', NULL, 'lainnya', '6/1/2026'),
(26, '200204152026031001', 'Pelaksana', '3/1/2026', '3/1/2026', 'utama', NULL),
(27, '200404122026032001', 'Pelaksana', '3/1/2026', '3/1/2026', 'utama', NULL),
(28, '198604072009022004', 'Kepala BPS Kabupaten Raja Ampat', '7/1/2026', '7/1/2026', 'utama', NULL)
ON CONFLICT (id) DO UPDATE 
SET jabatan = EXCLUDED.jabatan, tmt = EXCLUDED.tmt, jenis = EXCLUDED.jenis, tmt_selesai = EXCLUDED.tmt_selesai;

-- D. INSERT RIWAYAT_PANGKAT_GOLONGAN
INSERT INTO public.riwayat_pangkat_golongan (id, pegawai_nip, pangkat, golongan, tmt, tmt_ikut_pak)
VALUES
(1, '196803201994012001', 'Pembina Tk. I', 'IVb', '4/1/2015', '4/1/2015'),
(2, '198904192012111001', 'Penata Tk. I', 'IIId', '10/1/2022', '10/1/2022'),
(3, '198303182011011007', 'Penata', 'IIIc', '6/1/2024', '6/1/2024'),
(4, '197912122010032002', 'Penata Tk. I', 'IIId', '4/1/2022', '4/1/2022'),
(5, '199209162014121001', 'Penata', 'IIIc', '4/1/2023', '4/1/2023'),
(6, '199510152018021001', 'Penata', 'IIIc', '8/1/2024', '1/31/2024'),
(7, '198804022011011007', 'Penata Muda Tk. I', 'IIIb', '4/1/2023', '12/31/2022'),
(8, '199207162019031001', 'Penata Muda', 'IIIa', '3/1/2019', '3/1/2019'),
(9, '199610012019011003', 'Penata Muda Tk. I', 'IIIb', '2/1/2025', '8/31/2024'),
(10, '199504162018022001', 'Penata Muda Tk. I', 'IIIb', '4/1/2022', '4/1/2022'),
(11, '197809102007011002', 'Pengatur Tk. I', 'IId', '4/1/2019', '4/1/2019'),
(12, '198211202011012011', 'Penata Tk. I', 'IIId', '4/1/2023', '12/31/2022'),
(13, '198801242011012016', 'Penata Tk. I', 'IIId', '4/1/2023', '12/31/2022'),
(14, '199903302019121001', 'Pengatur', 'IIc', '12/1/2019', '12/1/2019'),
(15, '199801062019122001', 'Penata Muda', 'IIIa', '12/1/2019', '12/1/2019'),
(16, '198908262012112001', 'Penata Tk. I', 'IIId', '10/1/2022', '10/1/2022'),
(17, '199902212021042001', 'Penata Muda', 'IIIa', '4/1/2021', '4/1/2021'),
(18, '199903302022011001', 'Penata Muda', 'IIIa', '1/1/2022', '1/1/2022'),
(19, '199803012022032017', 'Pengatur', 'IIc', '3/1/2022', '3/1/2022'),
(20, '200003232023021002', 'Penata Muda', 'IIIa', '2/1/2023', '2/28/2023'),
(21, '200103272023102002', 'Penata Muda', 'IIIa', '10/1/2023', '10/31/2023'),
(22, '200107052024121001', 'Penata Muda', 'IIIa', '12/1/2024', '12/1/2024'),
(23, '199903302019121001', 'Pengatur Tk. I', 'IId', '10/1/2023', '12/31/2022'),
(24, '199207162019031001', 'Penata Muda Tk. I', 'IIIb', '6/1/2025', '7/31/2024'),
(25, '200204152026031001', 'Penata Muda', 'IIIa', '3/1/2026', '3/1/2026'),
(26, '200404122026032001', 'Pengatur', 'IIc', '3/1/2026', '3/1/2026'),
(27, '198604072009022004', 'Pembina', 'IVa', '8/1/2026', '8/1/2026')
ON CONFLICT (id) DO UPDATE 
SET pangkat = EXCLUDED.pangkat, golongan = EXCLUDED.golongan, tmt = EXCLUDED.tmt, tmt_ikut_pak = EXCLUDED.tmt_ikut_pak;

-- E. INSERT RIWAYAT_ANGKA_KREDIT
INSERT INTO public.riwayat_angka_kredit (id, pegawai_nip, angka_kredit, tmt, periode_tahun, periode_bulan_awal, periode_bulan_akhir, periode_label)
VALUES
(1, '197912122010032002', 103.152, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(2, '199209162014121001', 75.000, '9/1/2024', 2024, 9, 9, 'September 2024'),
(3, '199510152018021001', 0.000, '1/31/2024', 2024, 1, 1, 'Januari 2024'),
(4, '198804022011011007', 54.000, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(5, '199207162019031001', 50.400, '7/31/2024', 2024, 1, 7, 'Januari s.d Juli 2024'),
(6, '199610012019011003', 50.027, '8/31/2024', 2024, 1, 8, 'Januari s.d Agustus 2024'),
(7, '199504162018022001', 81.250, '10/31/2024', 2024, 1, 10, 'Januari s.d Oktober 2024'),
(8, '198211202011012011', 107.000, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(9, '198801242011012016', 107.000, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(10, '199903302019121001', 22.792, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(11, '199801062019122001', 8.149, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(12, '198908262012112001', 107.000, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(13, '199902212021042001', 16.372, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(14, '199903302022011001', 11.813, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(15, '199803012022032017', 5.135, '12/31/2022', 2022, 1, 12, 'Januari s.d Desember 2022'),
(16, '200003232023021002', 0.000, '2/28/2023', 2023, 2, 2, 'Februari 2023'),
(17, '200103272023102002', 0.000, '10/31/2023', 2023, 10, 10, 'Oktober 2023'),
(18, '200107052024121001', 0.000, '12/1/2024', 2024, 12, 12, 'Desember 2024'),
(19, '199903302022011001', 24.313, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(20, '199903302022011001', 36.813, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(21, '199903302022011001', 49.313, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(22, '199903302019121001', 27.792, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(23, '199903302019121001', 32.792, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(25, '199803012022032017', 10.135, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(26, '199803012022032017', 15.135, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(27, '199803012022032017', 20.135, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(28, '199801062019122001', 20.649, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(29, '199801062019122001', 33.149, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(30, '199801062019122001', 45.649, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(31, '198908262012112001', 132.000, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(32, '198908262012112001', 157.000, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(33, '198908262012112001', 182.000, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(34, '197912122010032002', 128.152, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(35, '197912122010032002', 153.152, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(36, '197912122010032002', 178.152, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(37, '199207162019031001', 55.608, '12/31/2024', 2024, 8, 12, 'Agustus s.d Desember 2024'),
(38, '199207162019031001', 68.108, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(39, '198804022011011007', 66.500, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(40, '198804022011011007', 79.000, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(41, '198804022011011007', 91.500, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(42, '199610012019011003', 54.715, '12/31/2024', 2024, 9, 12, 'September s.d Desember 2024'),
(43, '199610012019011003', 67.215, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(44, '199510152018021001', 30.208, '12/31/2024', 2024, 2, 12, 'Februari s.d Desember 2024'),
(45, '199510152018021001', 55.208, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(46, '199504162018022001', 83.855, '12/31/2024', 2024, 11, 12, 'November s.d Desember 2024'),
(47, '199504162018022001', 96.355, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(48, '198211202011012011', 132.000, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(49, '198211202011012011', 157.000, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(50, '198211202011012011', 182.000, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(51, '198801242011012016', 132.000, '12/31/2023', 2023, 1, 12, 'Januari s.d Desember 2023'),
(52, '198801242011012016', 157.000, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(53, '198801242011012016', 182.000, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(54, '200107052024121001', 12.500, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(55, '200103272023102002', 2.083, '12/31/2023', 2023, 11, 12, 'November s.d Desember 2023'),
(56, '200103272023102002', 14.583, '12/31/2024', 2024, 1, 12, 'Januari s.d Desember 2024'),
(57, '200103272023102002', 27.083, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025'),
(58, '199801062019122001', 50.337, '3/31/2026', 2026, 1, 3, 'Januari s.d Maret 2026'),
(61, '199903302019121001', 37.792, '12/31/2025', 2025, 1, 12, 'Januari s.d Desember 2025')
ON CONFLICT (id) DO UPDATE 
SET angka_kredit = EXCLUDED.angka_kredit, tmt = EXCLUDED.tmt, periode_label = EXCLUDED.periode_label;

-- F. INSERT RIWAYAT_GELAR
INSERT INTO public.riwayat_gelar (id, pegawai_nip, gelar_depan, gelar_belakang, tmt)
VALUES
(1, '196803201994012001', 'Ir.', NULL, '1/1/2015'),
(2, '198904192012111001', NULL, 'SST', '1/1/2015'),
(3, '198303182011011007', NULL, 'S.E.', '1/1/2015'),
(4, '197912122010032002', NULL, 'SE', '1/1/2015'),
(5, '199209162014121001', NULL, 'SST', '1/1/2015'),
(6, '199510152018021001', NULL, 'SST', '1/1/2015'),
(7, '198804022011011007', NULL, 'SE', '1/1/2015'),
(8, '199207162019031001', NULL, 'S.Si.', '1/1/2015'),
(9, '199610012019011003', NULL, 'S.Tr.Stat.', '1/1/2015'),
(10, '199504162018022001', NULL, 'SST', '1/1/2015'),
(11, '197809102007011002', NULL, NULL, '1/1/2015'),
(12, '198211202011012011', NULL, 'S.Kom.', '1/1/2015'),
(13, '198801242011012016', NULL, 'S.Sos.', '1/1/2015'),
(14, '199903302019121001', NULL, 'A.Md.Stat.', '1/1/2015'),
(15, '199801062019122001', NULL, 'S.Tr.Stat.', '1/1/2015'),
(16, '198908262012112001', NULL, 'SST, M.Ec.Dev', '1/1/2015'),
(17, '199902212021042001', NULL, 'S.Tr.Stat.', '1/1/2015'),
(18, '199903302022011001', NULL, 'S.Tr.Stat.', '1/1/2015'),
(19, '199803012022032017', NULL, 'A.Md', '1/1/2015'),
(20, '200003232023021002', NULL, 'S.Tr.Stat.', '1/1/2015'),
(21, '200103272023102002', NULL, 'S.Tr.Stat.', '1/1/2015'),
(22, '200107052024121001', NULL, 'S.Tr.Stat.', '1/1/2015'),
(23, '199209162014121001', NULL, 'SST, M.AP', '8/1/2024'),
(24, '200204152026031001', NULL, 'S.Tr.Stat.', '3/1/2026'),
(25, '200404122026032001', NULL, 'A.Md.Stat.', '3/1/2026'),
(26, '198604072009022004', NULL, 'SST, M.Ing.', '1/1/2015')
ON CONFLICT (id) DO UPDATE 
SET gelar_depan = EXCLUDED.gelar_depan, gelar_belakang = EXCLUDED.gelar_belakang, tmt = EXCLUDED.tmt;

-- 12. SINKRONISASI SEQUENCE ID SELURUH TABEL
SELECT setval(pg_get_serial_sequence('public.users', 'id'), COALESCE(max(id), 1)) FROM public.users;
SELECT setval(pg_get_serial_sequence('public.data_pegawai', 'id'), COALESCE(max(id), 1)) FROM public.data_pegawai;
SELECT setval(pg_get_serial_sequence('public.riwayat_jabatan', 'id'), COALESCE(max(id), 1)) FROM public.riwayat_jabatan;
SELECT setval(pg_get_serial_sequence('public.riwayat_pangkat_golongan', 'id'), COALESCE(max(id), 1)) FROM public.riwayat_pangkat_golongan;
SELECT setval(pg_get_serial_sequence('public.riwayat_angka_kredit', 'id'), COALESCE(max(id), 1)) FROM public.riwayat_angka_kredit;
SELECT setval(pg_get_serial_sequence('public.riwayat_gelar', 'id'), COALESCE(max(id), 1)) FROM public.riwayat_gelar;

-- ==============================================================================
-- 13. FUNGSI RPC: MANAJEMEN PENGGUNA (ADMIN ONLY)
-- ==============================================================================

-- A. Ambil Seluruh Data Pengguna untuk Halaman Admin
CREATE OR REPLACE FUNCTION public.admin_get_all_users()
RETURNS TABLE (
    id BIGINT,
    username TEXT,
    full_name TEXT,
    role TEXT,
    roles JSONB,
    must_change_password BOOLEAN,
    created_at TIMESTAMPTZ,
    last_login TIMESTAMPTZ,
    pegawai_nip TEXT,
    status_kepegawaian TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u.id,
        u.username,
        u.full_name,
        u.role,
        u.roles,
        u.must_change_password,
        u.created_at,
        u.last_login,
        dp.pegawai_nip,
        COALESCE(dp.status_kepegawaian, 'aktif') AS status_kepegawaian
    FROM public.users u
    LEFT JOIN public.data_pegawai dp ON lower(u.username) = lower(dp.username)
    ORDER BY u.id ASC;
END;
$$;

-- B. Tambah Pengguna Baru oleh Admin
CREATE OR REPLACE FUNCTION public.admin_create_user(
    p_username TEXT,
    p_full_name TEXT,
    p_password TEXT,
    p_roles JSONB,
    p_nip TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_user_id BIGINT;
    v_primary_role TEXT;
BEGIN
    p_username := lower(trim(p_username));
    p_full_name := trim(p_full_name);

    IF p_username = '' OR p_full_name = '' THEN
        RETURN jsonb_build_object('success', false, 'message', 'Username dan Nama Lengkap wajib diisi');
    END IF;

    -- Validasi 4: User minimal memiliki 1 role
    IF p_roles IS NULL OR jsonb_array_length(p_roles) = 0 THEN
        RETURN jsonb_build_object('success', false, 'message', 'User minimal harus memiliki 1 role');
    END IF;

    IF EXISTS (SELECT 1 FROM public.users WHERE lower(username) = p_username) THEN
        RETURN jsonb_build_object('success', false, 'message', 'Username sudah terdaftar');
    END IF;

    IF p_roles ? 'admin' THEN
        v_primary_role := 'admin';
    ELSE
        v_primary_role := 'user';
    END IF;

    INSERT INTO public.users (username, password_hash, must_change_password, full_name, role, roles)
    VALUES (
        p_username,
        extensions.crypt(p_password, extensions.gen_salt('bf', 10)),
        TRUE,
        p_full_name,
        v_primary_role,
        p_roles
    )
    RETURNING id INTO v_user_id;

    -- Hubungkan ke data_pegawai jika NIP diisi
    IF p_nip IS NOT NULL AND trim(p_nip) <> '' THEN
        INSERT INTO public.data_pegawai (username, pegawai_nip, status_kepegawaian)
        VALUES (p_username, trim(p_nip), 'aktif')
        ON CONFLICT (pegawai_nip) DO UPDATE SET username = EXCLUDED.username;
    END IF;

    RETURN jsonb_build_object('success', true, 'message', 'Pengguna berhasil ditambahkan', 'user_id', v_user_id);
END;
$$;

-- C. Perbarui Role / Hak Akses Pengguna oleh Admin
CREATE OR REPLACE FUNCTION public.admin_update_user_roles(
    p_username TEXT,
    p_roles JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_primary_role TEXT;
BEGIN
    p_username := lower(trim(p_username));

    -- Validasi 4: User minimal memiliki 1 role
    IF p_roles IS NULL OR jsonb_array_length(p_roles) = 0 THEN
        RETURN jsonb_build_object('success', false, 'message', 'User minimal harus memiliki 1 role!');
    END IF;

    -- Validasi 5: rizal.akbar adalah admin tetap (role admin tidak bisa dicabut)
    IF p_username = 'rizal.akbar' AND NOT (p_roles ? 'admin') THEN
        RETURN jsonb_build_object('success', false, 'message', 'Role admin untuk rizal.akbar tidak dapat dicabut (Admin Tetap)!');
    END IF;

    IF p_roles ? 'admin' THEN
        v_primary_role := 'admin';
    ELSE
        v_primary_role := 'user';
    END IF;

    UPDATE public.users
    SET role = v_primary_role,
        roles = p_roles
    WHERE lower(username) = p_username;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'Pengguna tidak ditemukan');
    END IF;

    RETURN jsonb_build_object('success', true, 'message', 'Role pengguna berhasil diperbarui');
END;
$$;

-- D. Reset Password Pengguna oleh Admin
CREATE OR REPLACE FUNCTION public.admin_reset_user_password(
    p_username TEXT,
    p_new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
    p_username := lower(trim(p_username));

    IF length(p_new_password) < 6 THEN
        RETURN jsonb_build_object('success', false, 'message', 'Password minimal 6 karakter');
    END IF;

    UPDATE public.users
    SET password_hash = extensions.crypt(p_new_password, extensions.gen_salt('bf', 10)),
        must_change_password = TRUE
    WHERE lower(username) = p_username;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'Pengguna tidak ditemukan');
    END IF;

    RETURN jsonb_build_object('success', true, 'message', 'Password berhasil direset. User wajib mengganti password saat login.');
END;
$$;

-- E. Hapus / Nonaktifkan Pengguna oleh Admin
CREATE OR REPLACE FUNCTION public.admin_delete_user(
    p_username TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    p_username := lower(trim(p_username));

    -- Validasi 5: rizal.akbar tidak boleh dihapus
    IF p_username = 'rizal.akbar' THEN
        RETURN jsonb_build_object('success', false, 'message', 'User rizal.akbar adalah Admin Tetap dan tidak dapat dihapus!');
    END IF;

    DELETE FROM public.users WHERE lower(username) = p_username;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'Pengguna tidak ditemukan');
    END IF;

    RETURN jsonb_build_object('success', true, 'message', 'Pengguna berhasil dihapus');
END;
$$;

