-- ==============================================================================
-- SCRIPT SETUP DATABASE SUPABASE: MODUL SURAT TUGAS & PERJALANAN DINAS (APA)
-- BPS KABUPATEN RAJA AMPAT
-- Jalankan seluruh script ini di menu "SQL Editor" pada dashboard Supabase Anda.
-- ==============================================================================

-- 1. TABEL KAMUS_POK (Mata Anggaran Kegiatan / POK)
CREATE TABLE IF NOT EXISTS public.kamus_pok (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_mak TEXT NOT NULL UNIQUE,
    deskripsi TEXT NOT NULL,
    tahun INT DEFAULT 2026,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_kamus_pok_kode ON public.kamus_pok(kode_mak);

-- 2. TABEL MITRA (Mitra Statistik dengan NIP placeholder MITRA-{tahun}-{id 3 digit})
CREATE TABLE IF NOT EXISTS public.mitra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mitra_nip TEXT NOT NULL UNIQUE,
    nama TEXT NOT NULL,
    jk TEXT DEFAULT 'Laki-laki',
    alamat TEXT,
    jabatan TEXT DEFAULT 'Mitra Statistik',
    posisi TEXT DEFAULT 'Petugas Pendataan Lapangan',
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mitra_nip ON public.mitra(mitra_nip);

-- 3. TABEL SURAT_TUGAS
CREATE TABLE IF NOT EXISTS public.surat_tugas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_surat TEXT,
    nomor_urut INT,
    tgl_surat TEXT,
    waktu_pelaksanaan TEXT NOT NULL,
    tgl_mulai TEXT,
    tgl_selesai TEXT,
    perihal TEXT NOT NULL,
    tempat_tujuan TEXT NOT NULL,
    pegawai_nip_list JSONB NOT NULL DEFAULT '[]'::jsonb,
    bertugas_sebagai JSONB DEFAULT '{}'::jsonb,
    menimbang TEXT,
    alat_angkutan TEXT DEFAULT 'Kendaraan Dinas / Sewa',
    pok_id TEXT,
    penandatangan_nip TEXT,
    tipe_surat TEXT DEFAULT 'surat_tugas',
    status TEXT DEFAULT 'menunggu', -- 'menunggu' | 'selesai'
    nomor_spd TEXT,
    nomor_spd_urut INT,
    jumlah_responden INT DEFAULT 1,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_surat_tugas_status ON public.surat_tugas(status);
CREATE INDEX IF NOT EXISTS idx_surat_tugas_created_by ON public.surat_tugas(created_by);
CREATE INDEX IF NOT EXISTS idx_surat_tugas_tgl ON public.surat_tugas(tgl_surat);

-- 4. PENGATURAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.kamus_pok ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mitra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.surat_tugas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access kamus_pok" ON public.kamus_pok;
CREATE POLICY "Public access kamus_pok" ON public.kamus_pok FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access mitra" ON public.mitra;
CREATE POLICY "Public access mitra" ON public.mitra FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access surat_tugas" ON public.surat_tugas;
CREATE POLICY "Public access surat_tugas" ON public.surat_tugas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 5. BUCKET STORAGE UNTUK TEMPLATE & PREVIEW DOKUMEN WORD
INSERT INTO storage.buckets (id, name, public)
VALUES 
    ('template', 'template', true),
    ('surat-tugas-preview', 'surat-tugas-preview', false)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

DROP POLICY IF EXISTS "Storage access template" ON storage.objects;
CREATE POLICY "Storage access template" ON storage.objects FOR ALL TO anon, authenticated USING (bucket_id = 'template') WITH CHECK (bucket_id = 'template');

DROP POLICY IF EXISTS "Storage access surat-tugas-preview" ON storage.objects;
CREATE POLICY "Storage access surat-tugas-preview" ON storage.objects FOR ALL TO anon, authenticated USING (bucket_id = 'surat-tugas-preview') WITH CHECK (bucket_id = 'surat-tugas-preview');

-- 6. SEED DATA KAMUS_POK (Daftar MAK Kegiatan BPS Kabupaten Raja Ampat)
INSERT INTO public.kamus_pok (kode_mak, deskripsi, tahun)
VALUES
    ('2901.BMA.006.051.A.524111', 'Belanja Perjalanan Dinas Biasa Subbagian Umum BPS Kabupaten Raja Ampat', 2026),
    ('2901.EBA.994.051.A.524111', 'Perjalanan Dinas Survei Angkatan Kerja Nasional (SAKERNAS) Semesteran', 2026),
    ('2901.EBA.994.051.B.524113', 'Perjalanan Dinas Survei Sosial Ekonomi Nasional (SUSENAS) Kor dan Konsumsi', 2026),
    ('2901.QDB.001.051.A.524111', 'Perjalanan Dinas Statistik Pertanian, Tanaman Pangan, Hortikultura, dan Perkebunan', 2026),
    ('2901.QDB.002.051.A.524111', 'Perjalanan Dinas Survei Perikanan dan Kelautan Wilayah Kepulauan Raja Ampat', 2026),
    ('2901.QDC.001.051.A.524111', 'Perjalanan Dinas Statistik Distribusi, Hotel, Restoran, dan Wisata Bahari', 2026),
    ('2901.QDC.002.051.A.524111', 'Perjalanan Dinas Survei Harga Produsen dan Konsumen Pedesaan', 2026),
    ('2901.QDD.003.051.A.524111', 'Perjalanan Dinas Neraca Wilayah, PDRB, dan Analisis Statistik Lintas Sektor', 2026),
    ('2901.QDE.004.051.A.524111', 'Perjalanan Dinas Integrasi Pengolahan, Diseminasi, dan Rekomendasi Statistik', 2026),
    ('2901.WA.001.051.A.524111', 'Perjalanan Dinas Pembinaan Desa Cinta Statistik (Desa Cantik) Raja Ampat', 2026)
ON CONFLICT (kode_mak) DO UPDATE 
SET deskripsi = EXCLUDED.deskripsi, tahun = EXCLUDED.tahun;

-- 7. SEED DATA MITRA (Daftar Mitra Statistik BPS Raja Ampat)
INSERT INTO public.mitra (mitra_nip, nama, jk, alamat, jabatan, posisi)
VALUES
    ('MITRA-2026-001', 'Yohanes Mambrasar', 'Laki-laki', 'Waisai Kota, Distrik Kota Waisai', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-002', 'Maria Dimara', 'Perempuan', 'Kelurahan Sapordanko, Distrik Kota Waisai', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-003', 'Simon Mayor', 'Laki-laki', 'Kampung Saonek, Distrik Waigeo Selatan', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-004', 'Naomi Fakdawer', 'Perempuan', 'Kampung Warsambin, Distrik Teluk Mayalibit', 'Mitra Statistik', 'Pemeriksa Lapangan'),
    ('MITRA-2026-005', 'Paulus Gaman', 'Laki-laki', 'Kampung Yenbeser, Distrik Waigeo Selatan', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-006', 'Beatrix Burdam', 'Perempuan', 'Waisai Kota, Distrik Kota Waisai', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-007', 'Markus Sauyai', 'Laki-laki', 'Kampung Friwen, Distrik Waigeo Selatan', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-008', 'Sarah Arfan', 'Perempuan', 'Kampung Lopintol, Distrik Teluk Mayalibit', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-009', 'Dominggus Rumbewas', 'Laki-laki', 'Kampung Yembekaki, Distrik Waigeo Timur', 'Mitra Statistik', 'Pencacah Lapangan'),
    ('MITRA-2026-010', 'Fransina Wader', 'Perempuan', 'Waisai Kota, Distrik Kota Waisai', 'Mitra Statistik', 'Pemeriksa Lapangan')
ON CONFLICT (mitra_nip) DO UPDATE 
SET nama = EXCLUDED.nama, jk = EXCLUDED.jk, alamat = EXCLUDED.alamat, jabatan = EXCLUDED.jabatan;

-- 8. FUNGSI RPC: AMBIL NOMOR URUT BERIKUTNYA UNTUK SURAT TUGAS & SPD
CREATE OR REPLACE FUNCTION public.get_next_nomor_surat_tugas(p_tahun INT)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_max INT;
BEGIN
    SELECT COALESCE(MAX(nomor_urut), 0) INTO v_max
    FROM public.surat_tugas
    WHERE (EXTRACT(YEAR FROM created_at) = p_tahun OR tgl_surat LIKE '%' || p_tahun::text || '%');

    RETURN v_max + 1;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_next_nomor_surat_tugas(INT) TO anon, authenticated;
